name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Python version
        run: |
          PYTHON_VERSION=$(cat my_file.txt)
          echo "Python Version: $PYTHON_VERSION"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '$PYTHON_VERSION'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: Run pytest
        run: pytest

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-coverage
          path: coverage.xml
        if: ${{ always() }}

      - name: Ruff check
        run: ruff check
